### ISSUE TITLE
UI updates 

### ISSUE THREAD

**Issue by Dev-Code24** [Shailendra1703/Array-Sorting-Visualizer#2]
UI updates

**Comment by Dev-Code24** [comment]
@Shailendra1703 assign this to me pls

**Comment by Shailendra1703** [comment]
@Dev-Code24  Thanks for your valuable contribution, can you send me its working link by hosting this on your GitHub , I want to see, how colors of the bars changes between light and dark mode.

**Comment by Dev-Code24** [comment]
@Shailendra1703 
yeah sure!
[](https://dev-code24.github.io/Array-Sorting-Visualizer/)

**Comment by Dev-Code24** [comment]
@Shailendra1703 
here is the link
https://dev-code24.github.io/Array-Sorting-Visualizer/

**Comment by Shailendra1703** [comment]
@Dev-Code24  it's good, light mode is good but, can you make the dark mode to default view (as it was before) , so that i can merge your pull request.

**Comment by Dev-Code24** [comment]
@Shailendra1703 
Yeah sure I'll update the P R

**Comment by Dev-Code24** [comment]
@Shailendra1703
I have made darkMode as the default mode for the users
reference issue: https://github.com/Shailendra1703/Array-Sorting-Visualizer/issues/2
reference PR : #3 

Video:
https://user-images.githubusercontent.com/97425135/194717415-0b9a2a21-c0d6-4401-8419-44903e4a9387.mov

**Comment by Shailendra1703** [comment]
> @Shailendra1703 I have made darkMode as the default mode for the users reference issue: #2 reference PR : #3
> 
> Video: https://user-images.githubusercontent.com/97425135/194717415-0b9a2a21-c0d6-4401-8419-44903e4a9387.mov

I was saying that make the dark mode looks like this

![image](https://user-images.githubusercontent.com/84718204/194737794-c0366a20-998a-4d60-9116-2eb71d1bf8fe.png)

As it was before, change the color of the buttons as they were before.

**Comment by Dev-Code24** [comment]
@Shailendra1703 
yeah, wait

**Comment by Dev-Code24** [comment]
> > @Shailendra1703 I have made darkMode as the default mode for the users reference issue: #2 reference PR : #3
> > Video: https://user-images.githubusercontent.com/97425135/194717415-0b9a2a21-c0d6-4401-8419-44903e4a9387.mov
> 
> I was saying that make the dark mode looks like this
> 
> ![image](https://user-images.githubusercontent.com/84718204/194737794-c0366a20-998a-4d60-9116-2eb71d1bf8fe.png)
> 
> As it was before, change the color of the buttons as they were before.

i have made the dark mode colors to its initial colors

https://user-images.githubusercontent.com/97425135/194746891-e16ba58f-c540-490a-8b0e-3943334e6e01.mov

**Comment by Shailendra1703** [comment]
You did a wonderful job 🤩 @Dev-Code24 
Thanks for your contribution, I'm merging your pull request.
